; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CheckPYME"
#define MyAppVersion "1.0"
#define MyAppPublisher "TFM_UEM_DiegoRam�rezGri�o"
#define MyAppURL "https://github.com/spaidyr/CheckPYME"
#define MyAppExeName "checkpyme.py"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{158C6D46-447F-47FC-AE8B-2BB3FAFB3E4B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\your_path\CheckPYME\LICENSE.txt
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\your_path\CheckPYME\Agent_Installer
OutputBaseFilename=CheckPYME
SetupIconFile=C:\your_path\CheckPYME\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: "{userdocs}\{#MyAppName}\modules"

[Files]
Source: "C:\your_path\CheckPYME\Agent\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\your_path\CheckPYME\Agent\certs\*"; DestDir: "{userdocs}\{#MyAppName}\certs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\your_path\CheckPYME\Agent\agent.json"; DestDir: "{userdocs}\{#MyAppName}"; Flags: ignoreversion
Source: "C:\your_path\CheckPYME\Agent\client.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\your_path\CheckPYME\Agent\config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\your_path\CheckPYME\Agent\elk_credentials.txt"; DestDir: "{userdocs}\{#MyAppName}"; Flags: ignoreversion
Source: "C:\your_path\CheckPYME\Agent\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\your_path\CheckPYME\handler\Installer\python-install.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "{#MyAppName}"; ValueData: """C:\Program Files\Python39\python.exe -m "" ""{app}\{#MyAppExeName}"""


[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\icon.ico"

[Run]
Filename: "{tmp}\python-install.exe"; Parameters: "/quiet InstallAllUsers=1 PrependPath=1"; StatusMsg: "Instalando Python..."

; Instala las dependencias
Filename: "C:\Program Files\Python39\python.exe"; Parameters: "-m pip install cryptography==40.0.2"; StatusMsg: "Instalando la biblioteca cryptography..."; Flags: runhidden
Filename: "C:\Program Files\Python39\python.exe"; Parameters: "-m pip install elasticsearch==8.8.0"; StatusMsg: "Instalando la biblioteca elasticsearch..."; Flags: runhidden
Filename: "C:\Program Files\Python39\python.exe"; Parameters: "-m pip install pytz==2023.3"; StatusMsg: "Instalando la biblioteca elasticsearch..."; Flags: runhidden

; Ejecuta tu aplicaci�n
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent


